{% set version = "1.0.7" %}

package:
  name: pytomlpp
  version: {{ version }}

source:
  # github tarball does not contain submodules, cf. dear-github/dear-github#214
  # in this case, we don't mind, because tomlplusplus is packaged separately...
  - url: https://github.com/bobfang1992/pytomlpp/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 81241d74ca08df1da5786d6ea2c448cf33d394a5d180c0175bd8f8c3adf20b90
    patches:
      - patches/0001-redirect-tomlplusplus-include-to-global-library-path.patch
  # ... however, we do include the toml-test submodule; keep in sync with
  # https://github.com/bobfang1992/pytomlpp/tree/master/tests/<commit>
  - git_url: https://github.com/BurntSushi/toml-test
    git_rev: 280497fa5f12e43d7233aed0d74e07ca61ef176b
    folder: tests/toml-test

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<37]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - pybind11 >=2.8,<2.9
    # pin exactly because that's what the upstream submodule does too
    - tomlplusplus ==2.5.0
  run:
    - python

test:
  requires:
    - pytest
    - python-dateutil
  source_files:
    - tests/
  imports:
    - pytomlpp
  commands:
    - pytest tests -v

about:
  home: https://github.com/bobfang1992/pytomlpp
  license: MIT
  license_file: LICENSE
  summary: A python wrapper for tomlplusplus
  dev_url: https://github.com/bobfang1992/pytomlpp

extra:
  recipe-maintainers:
    - h-vetinari
